### ISSUE TITLE
Dolphin's toolbar turn into white when open "About Dolphin"

### ISSUE THREAD

**Issue by archqob** [PapirusDevelopmentTeam/adapta-kde#51] opened 2018-04-21 18:21 UTC
Dolphin's toolbar turn into white when open "About Dolphin" From the submenu "Help"
Steps to reproduce showed in the following images:
1-
![1](https://user-images.githubusercontent.com/21042432/39087449-7ffae8ee-45a1-11e8-8eea-9c5df345eab2.png)
2-
![2](https://user-images.githubusercontent.com/21042432/39087451-83f74528-45a1-11e8-9d10-3bd52a9d2d9a.png)
3-
![3](https://user-images.githubusercontent.com/21042432/39087454-8c62b2e2-45a1-11e8-9052-0cda8fea3aad.png)

NOTES:
1- the toolbar returns to its original state when resizing dolphin window
2- This issue doesn't happen when use the menu instead of the toolbar to open "About Dolphin"

**Comment by varlesh** [comment] 2018-04-21 18:29
hm, it's starnge.. i can't reproduce this:
![image](https://user-images.githubusercontent.com/8083855/39087529-7626f288-45b3-11e8-97e7-8d219bcfb8fd.png)

**Comment by archqob** [comment] 2018-04-21 19:00
Try to open it while the menu is hidden, From toolbar "i mean from this highlighted button"
![screenshot_20180421_205911](https://user-images.githubusercontent.com/21042432/39087823-edb9cf3a-45a6-11e8-9070-19fd68d6063c.png)

**Comment by varlesh** [comment] 2018-04-23 06:10
@archqob Render bug fixed by Kvantum dev in fresh git-version... But  style not applied, because it's Dolphin bug. See more info here: https://github.com/tsujan/Kvantum/issues/202

**Closed by varlesh** 2018-04-23 06:10 UTC
Labels: upstream bug
